name: Moodle Plugin CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-22.04

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: 'postgres'
          POSTGRES_HOST_AUTH_METHOD: 'trust'
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3

      mariadb:
        image: mariadb:10
        env:
          MYSQL_USER: 'root'
          MYSQL_ALLOW_EMPTY_PASSWORD: "true"
          MYSQL_CHARACTER_SET_SERVER: "utf8mb4"
          MYSQL_COLLATION_SERVER: "utf8mb4_unicode_ci"
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 3

    strategy:
      fail-fast: false
      matrix:
        php: ['8.1']
        moodle-branch: ['MOODLE_402_STABLE']
        database: [mariadb]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          path: plugin

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ matrix.extensions }}
          ini-values: max_input_vars=5000
          # If you are not using code coverage, keep "none". Otherwise, use "pcov" (Moodle 3.10 and up) or "xdebug".
          # If you try to use code coverage with "none", it will fallback to phpdbg (which has known problems).
          coverage: none

      - name: Initialise moodle-plugin-ci
        env:
          COMPOSER_AUTH: '{"github-oauth": {"github.com": "${{secrets.github_token}}"} }'
        run: |
          composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^4
          pushd ci >/dev/null
            echo "> composer config repositories.repo-name vcs https://github.com/center-for-learning-management/moodle-psalm-plugin"
            composer config repositories.repo-name vcs https://github.com/center-for-learning-management/moodle-psalm-plugin
            echo "> composer require --dev center-for-learning-management/moodle-psalm-plugin dev-main@dev"
            composer require --dev center-for-learning-management/moodle-psalm-plugin dev-main@dev
          popd
          echo $(cd ci/bin; pwd) >> $GITHUB_PATH
          echo $(cd ci/vendor/bin; pwd) >> $GITHUB_PATH
          sudo locale-gen en_AU.UTF-8
          echo "NVM_DIR=$HOME/.nvm" >> $GITHUB_ENV

      - name: Install moodle-plugin-ci
        run: moodle-plugin-ci install --plugin ./plugin --db-host=127.0.0.1
        env:
          DB: ${{ matrix.database }}
          MOODLE_BRANCH: ${{ matrix.moodle-branch }}
          # Uncomment this to run Behat tests using the Moodle App.
          # MOODLE_APP: 'true'

      - name: PHP Lint
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci phplint

      - name: PHP Copy/Paste Detector
        continue-on-error: true # This step will show errors but will not fail
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci phpcpd

      - name: PHP Mess Detector
        continue-on-error: true # This step will show errors but will not fail
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci phpmd

      - name: Moodle Code Checker
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci phpcs --max-warnings 0

      - name: Moodle Code Beautifier and Fixer
        if: ${{ !cancelled() }}
        run: | 
          moodle-plugin-ci phpcbf

      - name: Moodle PHPDoc Checker
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci phpdoc --max-warnings 0

      - name: Validating
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci validate

      - name: Check upgrade savepoints
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci savepoints

      - name: Mustache Lint
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci mustache

      - name: Grunt
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci grunt --max-lint-warnings 0

      - name: PHP Lint --fix
        if: ${{ !cancelled() }}
        run: | 
          echo ">  find . -name Gruntfile.js"
          find . -name Gruntfile.js
          echo ">  grunt --gruntfile ${{ github.workspace }}/Gruntfile.js eslint --fix ${{ github.workspace }}/plugin/"
          grunt --gruntfile ${{ github.workspace }}/Gruntfile.js eslint --fix ${{ github.workspace }}/plugin/

      - name: PHPUnit tests
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci phpunit --fail-on-warning

      - name: Behat features
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci behat --profile chrome

      - name: Run Psalm
        if: ${{ !cancelled() }}
        run: |
          curl -sS https://raw.githubusercontent.com/center-for-learning-management/moodle-psalm-plugin/main/psalm-plugin.xml -o ci/psalm-plugin.xml
          curl -sS https://raw.githubusercontent.com/center-for-learning-management/moodle-psalm-plugin/main/issueHandlers.xml -o ci/issueHandlers.xml
          psalm --config=ci/psalm-plugin.xml --no-diff --show-info=true $(echo ${GITHUB_REPOSITORY}|cut -d/ -f2|sed s/^moodle-//|tr _ /)/

      - name: Copy changes to repository
        if: ${{ !cancelled() }}
        run: |
          echo "Copying changed files from ${{ github.workspace }}/moodle/$(echo ${GITHUB_REPOSITORY}|cut -d/ -f2|sed s/^moodle-//|tr _ /)/. to ${{ github.workspace }}/plugin/."
          rsync -av ${{ github.workspace }}/moodle/$(echo ${GITHUB_REPOSITORY}|cut -d/ -f2|sed s/^moodle-//|tr _ /)/. ${{ github.workspace }}/plugin/.
          
      - name: Get changed files
        if: ${{ !cancelled() }}
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          path: plugin

      - name: Create Pull Request
        if: |
          ${{ !cancelled() }} && steps.changed-files.outputs.only_changed != 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: CI Fixes
          title: Moodle CI Fixes
          body: |
           - Moodle CI Fixes
  
           Auto-generated by [create-pull-request][1]
  
           [1]: https://github.com/center-for-learning-management/moodle-local_experience/blob/$(echo ${{ github.workflow_ref }}|sed s#@refs/heads/##)
          branch: moodle-ci-fixes
          path: plugin

      - name: Mark cancelled jobs as failed.
        if: ${{ cancelled() }}
        run: exit 1
